### ISSUE TITLE
Panic if browser binary isn't found

### ISSUE THREAD

**Issue by taladar** [pwnwriter/haylxon#10]
Apparently if the browser binary is not found on the system hxn just panics.

There should be a better error message for this case, especially since the panic just mentions "No such file or directory" but not which path (semantically or the actual value) this refers to.

**Comment by pwnwriter** [comment]
Right now, i'm able to give some other hints too, but unble to remove panicking :(
![ok](https://user-images.githubusercontent.com/90331517/228277182-b0a9c15d-9c87-44fb-b5ee-9cf77209a381.png)

**Comment by pwnwriter** [comment]
Awh, that was smoooth, thanks 

![okk](https://user-images.githubusercontent.com/90331517/228296366-e6a45205-87fd-4111-8fe0-42e3a757464e.png)

**Comment by taladar** [comment]
You probably want to set the exit code to something other than 0 since 0 usually indicates a successful operation.
