### ISSUE TITLE
[pkg]: package hxn for `nix`

### ISSUE THREAD

**Issue by pwnwriter** [pwnwriter/haylxon#107]
### Description

Package and submit `hxn` for [`nix`](https://nixos.org)

**Comment by pwnwriter** [comment]
The package has been submitted . 

Tracking:- https://nixpk.gs/pr-tracker.html?pr=328651

Thanks @scientiac

**Comment by cyanw0lf** [comment]
The package is now available. The issue can be resolved by now.

**Comment by pwnwriter** [comment]
Yes the package is live : https://search.nixos.org/packages?channel=unstable&show=haylxon&from=0&size=50&sort=relevance&type=packages&query=hxn

**Comment by scientiac** [comment]
https://github.com/nix-community/nix-init


found this tool, it'll be useful for future packaging.
