### ISSUE TITLE
oneshot canceled

### ISSUE THREAD

**Issue by arjun0x1c** [pwnwriter/haylxon#124]
when i run hxn binary with chrome.. it throws error like this..

➜  ~ hxn -u https://example.com -b $(which chrome)
info: A directory already exists as hxnshots bumping ...
warning: oneshot canceled
info: Screenshots Taken and saved in directory hxnshots

i am using this latest chrome from (https://github.com/scheib/chromium-latest-linux)

I checked,
hxn has permission execute chrome binary
and the website also resolves.. but this error showns.

Thanks

**Comment by ErminMerdanovic** [comment]
Encountered the same issue today, how did you manage to resolve it?
