### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by ErminMerdanovic** [pwnwriter/haylxon#128]
### Description

Hi,

First of all, great job on your tool!

I tested it on my x64 demo VM, and it worked perfectly. Now, I’d like to deploy it with Chromium on my ARM server in Oracle. Before proceeding, I wanted to check if it has been tested on ARM architecture and whether it will run successfully in that environment.

Thanks!

**Comment by pwnwriter** [comment]
Hello @ErminMerdanovic , 

`Hxn` does work on ARM arch'es as well. You'll find already built binary in [releases](https://github.com/pwnwriter/haylxon/releases), if you don't want to build it from source. 

Have fun playin around. 

Cheers!
