### ISSUE TITLE
Add proxy flag

### ISSUE THREAD

**Issue by SharokhAtaie** [pwnwriter/haylxon#21]
Please add a proxy flag so that we can proxy requests to a SOCKS or something similar.

**Comment by pwnwriter** [comment]
Hey @SharokhAtaie,

I need to research on that. Give me some time :100:

**Comment by pwnwriter** [comment]
I've tried my best to implement proxy feature. I'm not getting my hands off... 

Do you have any comment @MrFixThis , probably some idea to implement proxy?

**Comment by SharokhAtaie** [comment]
You can read this tool and and find some information about proxy.
https://github.com/Sh1Yo/x8

**Comment by pwnwriter** [comment]
Seems promising :D

**Comment by MrFixThis** [comment]
Greetings guys. 
@pwnwriter let me do a little research first, please.
Once I'll get the concept, I'll write some code.

**Comment by pwnwriter** [comment]
Less gooo

**Comment by ssddOnTop** [comment]
hey @pwnwriter 
Are you planning to write own proxy server?

**Comment by pwnwriter** [comment]
Hello @ssddOnTop ,
I'm not sure, swamped with uni work, might not be able to. If someone from the community can resolve the issue, I'm good to merge the PR. 🦄

**Comment by pwnwriter** [comment]
I'm closing this issue since i haven't get any solution on this. Sorry wooopsie :(

**Comment by ssddOnTop** [comment]
@pwnwriter I have a solution, I tried a few things but looks like there's a problem with chromiumoxide dependency

however we can open chrome with command line args. You are already taking the path of chromium, you can simply remove the chromiumoxide dependency and use commandline args like: 
`chromium-browser --headless --screenshot="screenshot.png" --window-size=1920,1080 "http://example.com"`

you get more flexibility and can use arguments like`--disable-gpu` to make it more compatible
