### ISSUE TITLE
Option to use COOKIE from parent browser for a URL

### ISSUE THREAD

**Issue by shoutmarble** [pwnwriter/haylxon#24]
I would like an option to use a cookie from a signed in browser to Haylxon.

**Such as supplying an optional _-c_ option to use a cookie from parent browser, if that option hasn't been already taken**

The fetching of the cookie from the parent browser may be made dynamic based upon the supplied URL.

`hxn -b /usr/bin/brave-browser -u **-c** https://twitter.com`

Your choice of whether this should itself be another project.

**Comment by pwnwriter** [comment]
I'm closing this as not planned for now... If I get something that fits this issue... I'll surely give it a try .. thanks for raising this issue here . See ya <3
