### ISSUE TITLE
[bug] Produces a blank file

### ISSUE THREAD

**Issue by enomothem** [pwnwriter/haylxon#33]
### Description

I don't know if it's because of the title or the url, this screenshot doesn't have any content, but the size is assigned. I changed it to an image suffix, which is still an unsupported format.

### Software Version

0.1.8

### Steps to Reproduce

![image](https://github.com/pwnwriter/haylxon/assets/45089051/f3b47d00-f861-4590-8bf7-d30aa9fa2837)

I get a responsive page, but I get a 0 byte file, and I don't know why

### Expected Behavior

no image

### Actual Behavior

![image](https://github.com/pwnwriter/haylxon/assets/45089051/7dd83669-fe2e-4b08-a821-f93cf1679687)

**Comment by enomothem** [comment]
This seems to be related to ports and paths

**Comment by enomothem** [comment]
http://aaa.com/ --> http-aaa.com.png  
http://aaa.com:8080/ --> http-aaa.com

**Comment by pwnwriter** [comment]
mine works well with 
http://0.0.0.0:8000, 

![http-0 0 0 0:8000](https://github.com/pwnwriter/haylxon/assets/90331517/93b68533-cca0-4006-b43e-b98a94ffa005)

**Comment by enomothem** [comment]
I figured it out, because the colon: is an illegal character for windows

**Comment by enomothem** [comment]
https://github.com/pwnwriter/haylxon/pull/35/commits/8158ce79b127e607a3c09ccbbba0f027e8f95c08
After I changed the code and replaced it, the problem was solved
![image](https://github.com/pwnwriter/haylxon/assets/45089051/0da0e8d9-74ec-4a86-9fb7-b203ba27c855)
