### ISSUE TITLE
[bug] The CPU is still occupied after use

### ISSUE THREAD

**Issue by enomothem** [pwnwriter/haylxon#37]
### Description

我使用命令结束后，电脑风扇一直嗡嗡作响，我一看任务管理器，我滴妈妈耶，全是被占用的chrome进程，能否在结束后进行资源释放。

### Software Version

0.1.9

### Steps to Reproduce

![image](https://github.com/pwnwriter/haylxon/assets/45089051/d9e5e600-1941-4a93-98d9-b273a1f6bcb3)

### Expected Behavior

cpu ok

### Actual Behavior

cpu no space

**Comment by pwnwriter** [comment]
No, i cannot reprodue this behavior 

Vid -> https://0x0.st/HtF3.mp4

**Comment by enomothem** [comment]
Yeah, I watched your video.  Maybe it has something to do with windows' bad memory management

**Comment by pwnwriter** [comment]
oh, alright then,  I'm closing this issue
