### ISSUE TITLE
Haylxon works with brave 

### ISSUE THREAD

**Issue by LinuxNerdBTW** [pwnwriter/haylxon#7]
I build a haylxon from source , and it was tends to be work perfectly but its throw this error : 

thread 'main' panicked at 'An error occurred while running :(: "Could not auto detect a chrome executable"', src/main.rs:50:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

so basically it was searching for a chrome executable on my system . but it was not installed on my system , i have brave installed on my arch , so i resolved it by following trick : 

1. Copy /usr/bin/brave /usr/bin/chrome 
and it did trick , just worked !!!!!!!

if anyone using brave and trying out haylxon then do this , it will work .

**Comment by satvikpendem** [comment]
We should also allow the user to select the executable, probably works fine with any Chromium based ones but perhaps we could add a Safari and Firefox choice too.
